# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_IPOT <- function(mu, nu, C, beta, L, maxiter, abstol) {
    .Call('_T4transport_cpp_IPOT', PACKAGE = 'T4transport', mu, nu, C, beta, L, maxiter, abstol)
}

cpp_IPOT_WB <- function(C, Pk, beta, lambdas, L, maxiter, abstol) {
    .Call('_T4transport_cpp_IPOT_WB', PACKAGE = 'T4transport', C, Pk, beta, lambdas, L, maxiter, abstol)
}

cpp_Sinkhorn_Bregman <- function(mu, nu, costm, lambda, maxiter, abstol, printer) {
    .Call('_T4transport_cpp_Sinkhorn_Bregman', PACKAGE = 'T4transport', mu, nu, costm, lambda, maxiter, abstol, printer)
}

cpp_Sinkhorn_Cuturi <- function(a, b, costm, lambda, maxiter, abstol, printer) {
    .Call('_T4transport_cpp_Sinkhorn_Cuturi', PACKAGE = 'T4transport', a, b, costm, lambda, maxiter, abstol, printer)
}

extra_distmat <- function(X) {
    .Call('_T4transport_extra_distmat', PACKAGE = 'T4transport', X)
}

