# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_IPOT <- function(mu, nu, C, beta, L, maxiter, abstol) {
    .Call('_T4transport_cpp_IPOT', PACKAGE = 'T4transport', mu, nu, C, beta, L, maxiter, abstol)
}

cpp_Sinkhorn_Cuturi <- function(a, b, costm, lambda, maxiter, abstol) {
    .Call('_T4transport_cpp_Sinkhorn_Cuturi', PACKAGE = 'T4transport', a, b, costm, lambda, maxiter, abstol)
}

cpp_sinkhorn <- function(G, wx, wy, maxiter, abstol) {
    .Call('_T4transport_cpp_sinkhorn', PACKAGE = 'T4transport', G, wx, wy, maxiter, abstol)
}

rcpparma_hello_world <- function() {
    .Call('_T4transport_rcpparma_hello_world', PACKAGE = 'T4transport')
}

rcpparma_outerproduct <- function(x) {
    .Call('_T4transport_rcpparma_outerproduct', PACKAGE = 'T4transport', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_T4transport_rcpparma_innerproduct', PACKAGE = 'T4transport', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_T4transport_rcpparma_bothproducts', PACKAGE = 'T4transport', x)
}

