# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Barycenter_Proximal <- function(N, maxiter, abstol, listcXY, marginals, weights, lambda, printer) {
    .Call('_T4transport_C_Barycenter_Proximal', PACKAGE = 'T4transport', N, maxiter, abstol, listcXY, marginals, weights, lambda, printer)
}

C_Barycenter_Sinkhorn <- function(N, maxiter, abstol, listcXY, marginals, weights, lambda, printer) {
    .Call('_T4transport_C_Barycenter_Sinkhorn', PACKAGE = 'T4transport', N, maxiter, abstol, listcXY, marginals, weights, lambda, printer)
}

cpp_EPOT <- function(mu, nu, C, beta, L, maxiter, abstol, printer) {
    .Call('_T4transport_cpp_EPOT', PACKAGE = 'T4transport', mu, nu, C, beta, L, maxiter, abstol, printer)
}

cpp_IPOT <- function(mu, nu, C, beta, L, maxiter, abstol, printer) {
    .Call('_T4transport_cpp_IPOT', PACKAGE = 'T4transport', mu, nu, C, beta, L, maxiter, abstol, printer)
}

cpp_Sinkhorn_Subgradient <- function(a, b, M, regeps, maxIter = 1000L, tolerance = 0.0001) {
    .Call('_T4transport_cpp_Sinkhorn_Subgradient', PACKAGE = 'T4transport', a, b, M, regeps, maxIter, tolerance)
}

cpp_Sinkhorn_Bregman <- function(mu, nu, costm, lambda, maxiter, abstol, printer) {
    .Call('_T4transport_cpp_Sinkhorn_Bregman', PACKAGE = 'T4transport', mu, nu, costm, lambda, maxiter, abstol, printer)
}

cpp_Sinkhorn_Cuturi <- function(a, b, costm, lambda, maxiter, abstol, printer) {
    .Call('_T4transport_cpp_Sinkhorn_Cuturi', PACKAGE = 'T4transport', a, b, costm, lambda, maxiter, abstol, printer)
}

extra_pnorm <- function(x, y, p) {
    .Call('_T4transport_extra_pnorm', PACKAGE = 'T4transport', x, y, p)
}

extra_dist2mat <- function(X, Y, p) {
    .Call('_T4transport_extra_dist2mat', PACKAGE = 'T4transport', X, Y, p)
}

extra_dist2list <- function(X, dlist, p) {
    .Call('_T4transport_extra_dist2list', PACKAGE = 'T4transport', X, dlist, p)
}

extra_distmat <- function(X, p) {
    .Call('_T4transport_extra_distmat', PACKAGE = 'T4transport', X, p)
}

extra_vec_centering <- function(x) {
    .Call('_T4transport_extra_vec_centering', PACKAGE = 'T4transport', x)
}

extra_smooth_Subgradient <- function(a, b, M, regpar, maxiter, abstol) {
    .Call('_T4transport_extra_smooth_Subgradient', PACKAGE = 'T4transport', a, b, M, regpar, maxiter, abstol)
}

extra_L1_normalize <- function(x) {
    .Call('_T4transport_extra_L1_normalize', PACKAGE = 'T4transport', x)
}

extra_any_nan <- function(x) {
    .Call('_T4transport_extra_any_nan', PACKAGE = 'T4transport', x)
}

